In [1]:
#Answers for Question 3

In [2]:
dna = "ACTGATCGATTACGTATAGTATTTGCTATCATACATATATATCGATGCGTTCAT"

#Calculating AT content
length = len(dna)
a_content = dna.count('A')
t_content = dna.count('T')
at_content = (a_content + t_content)/length

print("AT content is: " + str(at_content))


AT content is: 0.6851851851851852


In [3]:
#Answers for Question 4

In [4]:
import numpy as np

In [5]:
#Check your understanding

mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20

print(mass)
print(age)

95.0
102


In [6]:
#Sorting out references

first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)

#The command returns Hopper Grace

Hopper Grace


In [7]:
#Slicing strings

element = 'oxygen'
print(element[:4])
#This command prints oxyg

print(element[4:])
#This command prints en

print(element[-1])
#This command prints n

print(element[-2])
#This command prints e

print(element[1:-1])
#This command prints xyge because it creates a substring starting after the first character and excludes the last character.

oxyg
en
n
e
xyge


In [8]:
#Thin slices

#Commands data[3:3, 4:4] and data[3:3, :] would both result in an empty string []

In [9]:
#Plot scaling

#matplotlib automatically sets the maximum and minimum values according to the data

#In order to obtain a more appropriate scale the following codes could be used. 
#axes3.set_ylabel('min')
#axes3.plot(np.min(data, axis=0))
#axes3.set_ylim(0,10)

In [10]:
#Drawing straight lines

#matplotlib takes the average values between points, thereby generating a straight line.

In [11]:
#Your own plot, assuming data values are saved as 'data'

#max_plot = matplotlib.pyplot.plot(np.std(data, axis=0))
#matplotlib.pyplot.show()

In [12]:
#Moving plots

import numpy as np
import matplotlib.pyplot

data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

# figure size
fig = matplotlib.pyploy.figure(figsize=(3.0, 10.0))

# adding sublots
axes1 = fig.add_subplot(3, 1, 1)
axes2 = fig.add_subplot(3, 1, 2)
axes3 = fig.add_subplot(3, 1, 3)

axes1.set_ylabel('average')
axes1.plot(np.mean(data, axis=0))

axes2.set_ylabel('max')
axes2.plot(np.max(data, axis=0))

axes3.set_ylabel('min')
axes3.plot(np.min(data, axis=0))

fig.tight_layout()

matplotlib.pyplot.show()

ImportError: No module named 'matplotlib'

In [13]:
#Stacking arrays

import numpy as np

A = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = np.hstack([A, A])
print('B = ')
print(B)

C = np.vstack([A, A])
print('C = ')
print(C)

D = np.hstack((A[:, :1], A[:, -1:]))
print('D = ')
print(D)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
D = 
[[1 3]
 [4 6]
 [7 9]]
